use serde::{Deserialize, Serialize};

use super::common::{MessageContent, Role};
use super::tool::ToolCall;

/// A chat message in the xAI Chat Completions API wire format.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Message {
    /// The role of the message author.
    pub role: Role,

    /// The content of the message, either a string or array of content blocks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<MessageContent>,

    /// Optional name for the participant (disambiguates same-role messages).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// When role is `tool`, the ID of the tool call this message is responding to.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,

    /// Tool calls generated by the model (present when role is `assistant`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

impl Message {
    /// Create a simple text message with the given role.
    pub fn text(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: Some(MessageContent::Text(content.into())),
            name: None,
            tool_call_id: None,
            tool_calls: None,
        }
    }

    /// Create an assistant message with tool calls and no text content.
    pub fn with_tool_calls(tool_calls: Vec<ToolCall>) -> Self {
        Self {
            role: Role::Assistant,
            content: None,
            name: None,
            tool_call_id: None,
            tool_calls: Some(tool_calls),
        }
    }

    /// Create a tool result message.
    pub fn tool_result(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: Some(MessageContent::Text(content.into())),
            name: None,
            tool_call_id: Some(tool_call_id.into()),
            tool_calls: None,
        }
    }
}

/// An input message for the Responses API.
///
/// The Responses API may use a slightly different input shape than the Chat
/// Completions API. This type captures the common structure; endpoint-specific
/// modules extend as needed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InputMessage {
    /// The role of the message author.
    pub role: Role,

    /// The content of the message.
    pub content: MessageContent,

    /// Optional name for the participant.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl InputMessage {
    /// Create a simple text input message.
    pub fn text(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: MessageContent::Text(content.into()),
            name: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::tool::{FunctionCall, ToolCall};

    #[test]
    fn message_text_round_trips() {
        let msg = Message::text(Role::User, "Hello, Grok!");
        let json = serde_json::to_string(&msg).unwrap();
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn message_skips_none_fields() {
        let msg = Message::text(Role::User, "hi");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("\"name\""));
        assert!(!json.contains("\"tool_call_id\""));
        assert!(!json.contains("\"tool_calls\""));
    }

    #[test]
    fn message_with_tool_calls_round_trips() {
        let tc = ToolCall {
            id: "call_123".into(),
            r#type: "function".into(),
            function: FunctionCall {
                name: "get_weather".into(),
                arguments: r#"{"city":"SF"}"#.into(),
            },
        };
        let msg = Message::with_tool_calls(vec![tc]);
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"tool_calls\""));
        // content should be omitted when None
        assert!(!json.contains("\"content\""));
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn tool_result_message_round_trips() {
        let msg = Message::tool_result("call_456", "result data");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"tool_call_id\":\"call_456\""));
        let back: Message = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn message_deserializes_with_unknown_fields() {
        // xAI may add fields; our types must tolerate them
        let json = r#"{
            "role": "assistant",
            "content": "hi",
            "some_future_field": 42
        }"#;
        let msg: Message = serde_json::from_str(json).unwrap();
        assert_eq!(msg.role, Role::Assistant);
    }

    #[test]
    fn input_message_round_trips() {
        let msg = InputMessage::text(Role::User, "prompt");
        let json = serde_json::to_string(&msg).unwrap();
        let back: InputMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, back);
    }

    #[test]
    fn input_message_skips_none_name() {
        let msg = InputMessage::text(Role::User, "prompt");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(!json.contains("\"name\""));
    }
}
