use serde::{Deserialize, Serialize};

/// A tool definition provided to the model for function calling.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolDefinition {
    /// The type of tool. Currently always `"function"`.
    pub r#type: String,
    /// The function definition.
    pub function: FunctionDefinition,
}

/// The definition of a callable function.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FunctionDefinition {
    /// The name of the function.
    pub name: String,
    /// A description of what the function does.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The JSON Schema describing the function's parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// A tool call generated by the model.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call.
    pub id: String,
    /// The type of tool call. Currently always `"function"`.
    pub r#type: String,
    /// The function call details.
    pub function: FunctionCall,
}

/// A specific function invocation within a tool call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FunctionCall {
    /// The name of the function to call.
    pub name: String,
    /// The arguments to pass, as a JSON string.
    pub arguments: String,
}

/// A tool definition for the xAI Responses API (flat schema).
///
/// Unlike the Chat Completions `ToolDefinition`, the Responses API uses a flat
/// structure where `name`, `description`, and `parameters` are top-level fields
/// alongside `type`.
///
/// Wire format: `{"type":"function","name":"...","description":"...","parameters":{...}}`
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResponsesToolDefinition {
    /// The type of tool. Currently always `"function"`.
    pub r#type: String,
    /// The name of the function.
    pub name: String,
    /// A description of what the function does.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The JSON Schema describing the function's parameters.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

/// A tool result message sent back to the model after executing a tool call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolResult {
    /// The ID of the tool call this result corresponds to.
    pub tool_call_id: String,
    /// The result content (typically a JSON string).
    pub content: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tool_definition_round_trips() {
        let td = ToolDefinition {
            r#type: "function".into(),
            function: FunctionDefinition {
                name: "get_weather".into(),
                description: Some("Get the current weather".into()),
                parameters: Some(serde_json::json!({
                    "type": "object",
                    "properties": {
                        "city": { "type": "string" }
                    },
                    "required": ["city"]
                })),
            },
        };
        let json = serde_json::to_string(&td).unwrap();
        let back: ToolDefinition = serde_json::from_str(&json).unwrap();
        assert_eq!(td, back);
    }

    #[test]
    fn tool_definition_skips_none_optional_fields() {
        let td = ToolDefinition {
            r#type: "function".into(),
            function: FunctionDefinition {
                name: "noop".into(),
                description: None,
                parameters: None,
            },
        };
        let json = serde_json::to_string(&td).unwrap();
        assert!(!json.contains("\"description\""));
        assert!(!json.contains("\"parameters\""));
    }

    #[test]
    fn tool_call_round_trips() {
        let tc = ToolCall {
            id: "call_abc123".into(),
            r#type: "function".into(),
            function: FunctionCall {
                name: "search".into(),
                arguments: r#"{"query":"rust"}"#.into(),
            },
        };
        let json = serde_json::to_string(&tc).unwrap();
        let back: ToolCall = serde_json::from_str(&json).unwrap();
        assert_eq!(tc, back);
    }

    #[test]
    fn tool_result_round_trips() {
        let tr = ToolResult {
            tool_call_id: "call_abc123".into(),
            content: r#"{"temp": 72}"#.into(),
        };
        let json = serde_json::to_string(&tr).unwrap();
        let back: ToolResult = serde_json::from_str(&json).unwrap();
        assert_eq!(tr, back);
    }

    #[test]
    fn responses_tool_definition_round_trips() {
        let td = ResponsesToolDefinition {
            r#type: "function".into(),
            name: "get_weather".into(),
            description: Some("Get the current weather".into()),
            parameters: Some(serde_json::json!({
                "type": "object",
                "properties": {
                    "city": { "type": "string" }
                },
                "required": ["city"]
            })),
        };
        let json = serde_json::to_string(&td).unwrap();
        // Verify flat structure: name is at top level, not nested under "function"
        assert!(json.contains("\"name\":\"get_weather\""));
        assert!(!json.contains("\"function\":{"));
        let back: ResponsesToolDefinition = serde_json::from_str(&json).unwrap();
        assert_eq!(td, back);
    }

    #[test]
    fn responses_tool_definition_skips_none_optional_fields() {
        let td = ResponsesToolDefinition {
            r#type: "function".into(),
            name: "noop".into(),
            description: None,
            parameters: None,
        };
        let json = serde_json::to_string(&td).unwrap();
        assert!(!json.contains("\"description\""));
        assert!(!json.contains("\"parameters\""));
    }

    #[test]
    fn responses_tool_definition_deserializes_from_wire() {
        let json = r#"{"type":"function","name":"search","description":"Search the web","parameters":{"type":"object","properties":{"q":{"type":"string"}}}}"#;
        let td: ResponsesToolDefinition = serde_json::from_str(json).unwrap();
        assert_eq!(td.name, "search");
        assert_eq!(td.description.as_deref(), Some("Search the web"));
        assert!(td.parameters.is_some());
    }

    #[test]
    fn tool_call_deserializes_with_unknown_fields() {
        let json = r#"{
            "id": "call_1",
            "type": "function",
            "function": { "name": "f", "arguments": "{}" },
            "index": 0
        }"#;
        let tc: ToolCall = serde_json::from_str(json).unwrap();
        assert_eq!(tc.id, "call_1");
    }
}
